pruebaAjax:
   path: /Ajax/{ajax}
   defaults: { _controller: LoginfirstBundle:Cliente:ajax} 
pruebaCliente:
   path: /prueba
   defaults: { _controller: LoginfirstBundle:Cliente:addCliente} 
pruebaAjax1:
   path: /Ajax/
   defaults: { _controller: LoginfirstBundle:Admin:ajax1} 
ver_articulos:
    pattern:  /ver-articulos
    defaults: { _controller: LoginfirstBundle:Cliente:verdatos }
   
   #fin ajax

estatica_Contactos:
    path: /Contactos
    defaults: { _controller: LoginfirstBundle:Default:Contactos}
estatica_Nosotros:
    path: /Nosotros
    defaults: { _controller: LoginfirstBundle:Default:Nosotros}
estatica_QS:
    path: /QuienesSomos
    defaults: { _controller: LoginfirstBundle:Default:QS}

estatica_MV:
    path: /Mision&Vision
    defaults: { _controller: LoginfirstBundle:Default:MV}

estatica_Productos:
    path: /Productos
    defaults: { _controller: LoginfirstBundle:Default:Productos}
#==============================login usuario===================
Login:
    path: /Login
    defaults: { _controller: LoginfirstBundle:Login:Perfiles}

Logout:
    path: /logout
    defaults: { _controller: LoginfirstBundle:Login:Logout}
    

    #=========================routing cliente==============================
Cliente:
    path: /Cliente
    defaults: { _controller: LoginfirstBundle:Cliente:Cliente}
    #-------------Actualiza Datos Cliente----------------------------
UpdateCliente:
    path: /UpdateCliente/
    defaults: { _controller: LoginfirstBundle:Cliente:updateCliente}
GuardarUpdate:
    path: /UpdateCliente/{Cliente}
    defaults: { _controller: LoginfirstBundle:Cliente:GuardarCliente}
    #----Atualiza Clave Clientes-----------------------------------
CambiarClaveCliente:
    path: /CambiarCClave/
    defaults: { _controller: LoginfirstBundle:Cliente:CambiarClave}     
PruebaClave:
    path: /CambiarCClave/{Cliente}
    defaults: { _controller: LoginfirstBundle:Cliente:PruebaClaveCliente}   
GuardaClave:
    path: /CambiarCClave/Guardar/{Cliente}
    defaults: {_controller: LoginfirstBundle:Cliente:GuardarClaveCliente}
    
    #-------ingreso Requerimientos clientes--#
NuevoReq:
    path: /NuevoRq
    defaults: { _controller: LoginfirstBundle:Cliente:NuevoRq}      
SubMenus:
    path: /SubMenusAjax/{idMenu}
    defaults: { _controller: LoginfirstBundle:Cliente:SubMenuAjax}
SubMenus1:
    path: /SubMenusAjax/
    defaults: { _controller: LoginfirstBundle:Cliente:SubMenusAjax}   
    
GuardarReqCliente:
    path: /GuardarRq/
    defaults: { _controller: LoginfirstBundle:Cliente:GuardarRqCliente}
    #-----------Actualiza requererimiento-------------------------
ActualizaReq1:
    path: /ActualizaReq
    defaults: { _controller: LoginfirstBundle:Cliente:ActualizaRequerimiento}
ActualizaReq:
    path: /ActualizaReq/{idRq}
    defaults: { _controller: LoginfirstBundle:Cliente:ActualizaRequerimiento}
    
    #-------------Eliminar requerimiento------------------------
EliminaReq1:
    path: /EliminarReq
    defaults: { _controller: LoginfirstBundle:Cliente:EliminarRequerimiento}
EliminaReq:
    path: /EliminarReq/{idRq}
    defaults: { _controller: LoginfirstBundle:Cliente:EliminarRequerimiento}
    
    #-----------Consulta requerimientos clientes====================
    #=====consulta desde Ingreso requerimiento==============================   
RequerimientosClientes:
    path: /ConsultaReqC/
    defaults: { _controller: LoginfirstBundle:Cliente:ConsultaReq}

RequerimientosModulosClientes:
    path: /ConsultaReqC/Modulo/{IdModulo}
    defaults: { _controller: LoginfirstBundle:Cliente:ConsultaModuloClientes}
        
    #========consulta desde consultas requerimientos===============
RequerimientosC:
    path: /RequerimientosC
    defaults: { _controller: LoginfirstBundle:Cliente:RequerimientosC}

RequerimientosCFechaInicial:
    path: /RequerimientosC/FechaInicialC
    defaults: { _controller: LoginfirstBundle:Cliente:RequerimientosFechaInicialC}

RequerimientosCEntreFechas:
    path: /RequerimientosC/FechaEntreFechasC
    defaults: { _controller: LoginfirstBundle:Cliente:RequerimientosEntreFechasC}
    
RequerimientosCEstados:
    path: /RequerimientosC/Estados
    defaults: { _controller: LoginfirstBundle:Cliente:RequerimientosEntreFechasC}
       
RequerimientosEstadosC:
    path: /RequerimientosC/Estados/{IdEstado}
    defaults: { _controller: LoginfirstBundle:Cliente:ConsultaEstadosC}
    
RequerimientosModulos:
    path: /RequerimientosC/Modulos/{IdModulo}
    defaults: { _controller: LoginfirstBundle:Cliente:ConsultaModulosC}    
    
      
    
  #----------------------routing empleados-----------------------------------  
Empleado:
    path: /Empleado
    defaults: { _controller: LoginfirstBundle:Empleado:Empleado}
    
RegistroT:
    path: /RegistroT/
    defaults: { _controller: LoginfirstBundle:Empleado:RegistroT}    
    
RegistroTiempo:
    path: /RegistroT/{idEmpresa}
    defaults: { _controller: LoginfirstBundle:Empleado:RequerimientoEmp}
GuardarHojasT:
    path: /GuardarTiempo/
    defaults: { _controller: LoginfirstBundle:Empleado:GuardarRegistroT}    
GuardarTiempoRq:
    path: /GuardarTiempo/Hojas/
    defaults: { _controller: LoginfirstBundle:Empleado:GuardarRegistroT} 
    
    
UpdateEmpleado:
    path: /UpdateEmpleado/
    defaults: { _controller: LoginfirstBundle:Empleado:updateEmpleado}
    
GuardarUpdateE:
    path: /UpdateEmpleado/{Empleado}
    defaults: { _controller: LoginfirstBundle:Empleado:GuardarEmpleado}
   
    
    #----actualiza clave Empleado---#
CambiarClaveEmpleado:
    path: /CambiarEClave/
    defaults: { _controller: LoginfirstBundle:Empleado:CambiarClave}     
PruebaClaveE:
    path: /CambiarEClave/{Empleado}
    defaults: { _controller: LoginfirstBundle:Empleado:PruebaClaveEmpleado}   
GuardaClaveE:
    path: /CambiarEClave/Guardar/{Empleado}
    defaults: {_controller: LoginfirstBundle:Empleado:GuardarClaveEmpleado}  
    
GuardarHojaT:
    path: /RegistroRq/
    defaults: {_controller: LoginfirstBundle:Empleado:GuardarReqTiempo}
    
    
Perfil:
    path: /perfil
    defaults: { _controller: LoginfirstBundle:Admin:ConsultaPerfil}
        
AdminConsulta:
    path: /AdminConsulta
    defaults: { _controller: LoginfirstBundle:Admin:ConsultaDatos}

    
GuardarRq:
    path: /GuardarRq
    defaults: { _controller: LoginfirstBundle:Cliente:GuardarRq}
    
ConsultaRq:
    path: /ConsultaRq
    defaults: { _controller: LoginfirstBundle:Cliente:ConsultaRq}
    
ConsultaEstado:
    path: /consulta/{id}
    defaults: { _controller: LoginfirstBundle:Cliente:Estados}
    
#==========================ROUTING ADMINISTRADOR================================== 
Admin:
    path: /Admin
    defaults: { _controller: LoginfirstBundle:Admin:Admin}

#ACTUALIZA DATOS
ActualizaDatos:
    path: /Actualiza/
    defaults: {_controller: LoginfirstBundle:Admin:ActualizaDatos}
GuardaDatosAdmin:
    path: /Actualiza/{idAdmin}
    defaults: {_controller: LoginfirstBundle:Admin:GuardarDatosAdmin}

ActualizaClaveAdmin:
    path: /ActualizaClave/
    defaults: {_controller: LoginfirstBundle:Admin:ActualizaClave} 
PruebaClaveAdmin:
    path: /ActualizaClave/{idAdmin}
    defaults: {_controller: LoginfirstBundle:Admin:PruebaClave}
GuardaClaveA:
    path: /ActualizaClave/GuardarA/{idAdmin}
    defaults: {_controller: LoginfirstBundle:Admin:GuardarClaveAdmin}
#==========consulta de empleados desde administrador
ConsultaEmpleados:
    path: /Empleados
    defaults: { _controller: LoginfirstBundle:Admin:ListarEmpleados}
GuardarEmpleado:
    path: /GuardarEmpleado
    defaults: { _controller: LoginfirstBundle:Admin:GuardarNuevoEmpleado}
GuardarEditEmpleado1:
    path: /Guardar/Editar
    defaults: { _controller: LoginfirstBundle:Admin:GuardarEditEmpleado}

GuardarEditEmpleado:
    path: /Guardar/Editar/{idEU}
    defaults: { _controller: LoginfirstBundle:Admin:GuardarEditEmpleado}
    
BuscaPorCedula:    
    path: /Cedula/
    defaults: { _controller: LoginfirstBundle:Admin:BuscaCedula}
BuscaPorCedula1:    
    path: /Cedula/{idCedula}
    defaults: { _controller: LoginfirstBundle:Admin:BuscaCedula}



EliminarEmpleado1:
    path: /Empleado/Eliminar
    defaults: { _controller: LoginfirstBundle:Admin:EliminarEmpleados}

EliminarEmpleado:
    path: /Empleado/Eliminar/{idED}
    defaults: { _controller: LoginfirstBundle:Admin:EliminarEmpleados}
#CLIENTES
ConsultaClientes:
    path: /Clientes
    defaults: { _controller: LoginfirstBundle:Admin:ListarClientes}
GuardarCliente:
    path: /GuardarCliente
    defaults: { _controller: LoginfirstBundle:Admin:GuardarNuevoCliente}
    
BuscaPorRuc:    
    path: /Ruc/
    defaults: { _controller: LoginfirstBundle:Admin:BuscaRuc}
    
BuscaPorRuc1:    
    path: /Ruc/{idRuc}
    defaults: { _controller: LoginfirstBundle:Admin:BuscaRuc}
    
GuardarEditCliente1:
    path: /Guardar/EditarC
    defaults: { _controller: LoginfirstBundle:Admin:GuardarEditarCliente}
    
GuardarEditCliente:
    path: /Guardar/EditarC/{idCU}
    defaults: { _controller: LoginfirstBundle:Admin:GuardarEditarCliente}
 
EliminarCliente1:
    path: /Cliente/Eliminar
    defaults: { _controller: LoginfirstBundle:Admin:EliminarCliente}   
    
EliminarCliente:
    path: /Cliente/Eliminar/{idCD}
    defaults: { _controller: LoginfirstBundle:Admin:EliminarCliente}
#MODULOS
ConsultaModulos:
    path: /Modulos
    defaults: { _controller: LoginfirstBundle:Admin:ListarModulos}
GuardarModulo:
    path: /GuardarModulo
    defaults: { _controller: LoginfirstBundle:Admin:GuardarNuevoModulo}  
    
GuardarEditModuloA1:
    path: /Guardar/EditarModulo
    defaults: { _controller: LoginfirstBundle:Admin:GuardarEditarCliente}
    
GuardarEditMenusA:
    path: /Guardar/Editarmenu/{idMenu}
    defaults: { _controller: LoginfirstBundle:Admin:GuardarEditarMenu}  

GuardarEditMenusA1:
    path: /Guardar/EditarModulo
    defaults: { _controller: LoginfirstBundle:Admin:GuardarEditarModulo}
    
GuardarEditModuloA:
    path: /Guardar/EditarModulo/{idModulo}
    defaults: { _controller: LoginfirstBundle:Admin:GuardarEditarModulo}
    
ActivaMod:
    path: /Modulo/Activa/{idMod}
    defaults: { _controller: LoginfirstBundle:Admin:ActivaModulo}
    
DesactivaMod:
    path: /Modulo/Desactiva/{idMod}
    defaults: { _controller: LoginfirstBundle:Admin:DesactivaModulo}
    
EliminarModulo:
    path: /Modulo/Eliminar/{idEM}
    defaults: { _controller: LoginfirstBundle:Admin:EliminarModulo}    
    
#MENUS
ConsultaMenus:
    path: /Menus
    defaults: { _controller: LoginfirstBundle:Admin:ListarMenus}
    
EliminarMenu:
    path: /Menu/Eliminar/{idEMe}
    defaults: { _controller: LoginfirstBundle:Admin:EliminarMenu} 
    
EliminarSubmenus1:
    path: /Submenu/Eliminar
    defaults: { _controller: LoginfirstBundle:Admin:EliminarSubmenus}   
    
EliminarSubmenus:
    path: /Submenu/Eliminar/{idSm}
    defaults: { _controller: LoginfirstBundle:Admin:EliminarSubmenus} 
    
ActivaMenu:
    path: /Menu/Activa/{idMenu}
    defaults: { _controller: LoginfirstBundle:Admin:ActivaMenu}
    
DesactivaMenu:
    path: /Menu/Desactiva/{idMenu}
    defaults: { _controller: LoginfirstBundle:Admin:DesactivaMenu}
GuardarMenu:
    path: /GuardarMenu
    defaults: { _controller: LoginfirstBundle:Admin:GuardarNuevoMenu}   
#SUBMENUS
#consulta Ajax
Menus:
    path: /Menus/{idModulo}
    defaults: { _controller: LoginfirstBundle:Admin:menu}
Menus1:
    path: /Menus/
    defaults: { _controller: LoginfirstBundle:Admin:menus}
#------------------------------------------------------------
ConsultaSubMenus:
    path: /SubMenus/
    defaults: { _controller: LoginfirstBundle:Admin:ListarSubMenus}
ActivaSubMenu:
    path: /SubMenu/Activa/{idSubMenu}
    defaults: { _controller: LoginfirstBundle:Admin:ActivaSubMenu}
DesactivaSubMenu:
    path: /SubMenu/Desactiva/{idSubMenu}
    defaults: { _controller: LoginfirstBundle:Admin:DesactivaSubMenu}
GuardarSubMenu:
    path: /GuardarSubMenu
    defaults: { _controller: LoginfirstBundle:Admin:GuardarNuevoSubMenu}    

GuardarEditSubMenusA1:
    path: /Guardar/EditarSubMenu
    defaults: { _controller: LoginfirstBundle:Admin:GuardarEditarSubMenu}
    
GuardarEditSubMenusA:
    path: /Guardar/EditarSubMenu/{idSubMenu}
    defaults: { _controller: LoginfirstBundle:Admin:GuardarEditarSubMenu}
#ASIGNACION REQUERIMIENTOS    
ConsultarRequerimientos:
    path: /Requerimientos
    defaults: { _controller: LoginfirstBundle:Admin:ListarRequerimientos}

GuardarAsignacion:
    path: /Asignar/{idRq}
    defaults: { _controller: LoginfirstBundle:Admin:Asignar}
#CONSULTAS ADMINISTRADOR =====con ajax
Requerimientos:
    path: /ConsultaReq/
    defaults: { _controller: LoginfirstBundle:Admin:ConsultaReq}

ConsultaTiempos:
    path: /C_Tiempos/
    defaults: { _controller: LoginfirstBundle:Admin:ConsultaTiempos}

ConsultaTiempos1:
    path: /C_Tiempos/Cliente/{idCliente}
    defaults: { _controller: LoginfirstBundle:Admin:ConsultaTiemposC}
    
ConsultaEmpleados:
    path: /C_Empleados/
    defaults: { _controller: LoginfirstBundle:Admin:ConsultaEmpleados}

ConsultaClientes:
    path: /C_Clientes/
    defaults: { _controller: LoginfirstBundle:Admin:ConsultaClientes}

ConsultaModulos:
    path: /C_Modulos/
    defaults: { _controller: LoginfirstBundle:Admin:ConsultaModulos}

    
RequerimientosFechaI:
    path: /ConsultaReq/FechaInicial
    defaults: { _controller: LoginfirstBundle:Admin:ConsultaReqFechaInicial}
   
RequerimientosFechas:
    path: /ConsultaReq/Fechas
    defaults: { _controller: LoginfirstBundle:Admin:ConsultaReqFechas}
    
RequerimientosCliente:
    path: /ConsultaReq/Cliente/{IdCliente}
    defaults: { _controller: LoginfirstBundle:Admin:ConsultaClientes}
RequerimientosEstado:
    path: /ConsultaReq/Estado/{IdEstado}
    defaults: { _controller: LoginfirstBundle:Admin:ConsultaEstado}
    
RequerimientosModulo:
    path: /ConsultaReq/Modulo/{IdModulo}
    defaults: { _controller: LoginfirstBundle:Admin:ConsultaModulo}
    
RequerimientosEmpleado:
    path: /ConsultaReq/Empleado/{IdEmpleado}
    defaults: { _controller: LoginfirstBundle:Admin:ConsultaEmpleado}
    
    
#consulta de empleados
ConsulReqEmp:
    path: /ConsultaReqE
    defaults: { _controller: LoginfirstBundle:Empleado:ConsultaReqE}
    
ConsulReqTiempos:
    path: /ConsulReqTiempos
    defaults: { _controller: LoginfirstBundle:Empleado:ConsulReqTiempos}


#busc de submenus
BuscaSubmenu:
    path: /Submenu/Busca/{idSub}
    defaults: { _controller: LoginfirstBundle:Admin:BuscaSubmenu}
    